version: 0.0
os: linux
files:
  - source: /
    destination: /var/github.com/o3labs/openpoint/
overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
